services:
  api:
    build: ./api
    container_name: api_c
    ports:
      - "4000:4000"
    volumes:
      - ./api:/app
      - ./api/node_modules:/app/node_modules
  mobile-app:
    build: ./mobile-app
    container_name: mobile-app_c
    ports:
      - "8081:8081"
    volumes:
      - ./mobile-app:/app
      - ./mobile-app/node_modules:/app/node_modules
    stdin_open: true
    tty: true
